package com.riverflow.model.mongodb;

import com.riverflow.model.mongodb.subdocuments.*;
import lombok.*;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.index.TextIndexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * Main MongoDB document for storing mindmaps
 */
@Document(collection = "mindmaps")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Mindmap {
    
    @Id
    private String id;
    
    @Indexed
    private Long mysqlUserId; // Owner user ID from MySQL database
    
    @TextIndexed
    @Indexed
    private String title;
    
    @TextIndexed
    private String description;
    
    private String thumbnail; // URL to mindmap thumbnail image
    
    @Builder.Default
    private List<Node> nodes = new ArrayList<>();
    
    @Builder.Default
    private List<Edge> edges = new ArrayList<>();
    
    private MindmapSettings settings;
    
    @Indexed
    private Boolean isPublic = false; // Whether mindmap is publicly accessible
    
    @Indexed
    private String shareToken; // Token for public sharing link
    
    @Builder.Default
    private List<Collaborator> collaborators = new ArrayList<>();
    
    private List<String> tags;
    
    private String category; // work, personal, education, project, brainstorming, ai-generated, other
    
    private Boolean isFavorite = false; // Marked as favorite by owner
    
    private Boolean isTemplate = false; // Can be used as a template
    
    @Indexed
    private String status = "active"; // active, archived, deleted
    
    // AI Integration
    private Boolean aiGenerated = false; // Generated by AI workflow
    private Long aiWorkflowId; // MySQL AI workflow ID if generated by AI
    private Map<String, Object> aiMetadata; // AI generation metadata
    
    // Metadata
    private MindmapMetadata metadata;
    
    @Indexed
    private LocalDateTime createdAt;
    
    @Indexed
    private LocalDateTime updatedAt;
}

