# Local Development Configuration
# Gmail App Password for sending emails (không commit file này!)
SPRING_MAIL_PASSWORD=fjzaeivwjhblsvig

# OPENAI CONFIGURATION (local)
gemini.base-url=${GEMINI_BASE_URL:https://generativelanguage.googleapis.com}
gemini.api-key=${GEMINI_API_KEY:AIzaSyDGLJD28duUxMN-qIIkn8Iv8phO3jiinPg}
gemini.model=${GEMINI_MODEL:gemini-2.5-flash}
