package com.riverflow.dto.mindmap;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DTO for generated mindmap node from AI
 * 
 * Represents a single node generated by AI with:
 * - node_title: tiêu đề của node mới
 * - node_summary: mô tả ngắn gọn
 * - parent_id: id node cha (nếu có)
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class GeneratedMindmapNode {
    
    /**
     * Tiêu đề của node mới
     */
    @JsonProperty("node_title")
    private String nodeTitle;
    
    /**
     * Mô tả ngắn gọn của node
     */
    @JsonProperty("node_summary")
    private String nodeSummary;
    
    /**
     * ID của node cha (nếu có)
     */
    @JsonProperty("parent_id")
    private String parentId;
}

