CREATE TABLE IF NOT EXISTS payment_transactions (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    external_id BIGINT UNSIGNED NULL,
    gateway VARCHAR(50) NOT NULL,
    transaction_date TIMESTAMP NULL,
    account_number VARCHAR(32) NULL,
    code VARCHAR(64) NULL,
    content TEXT NULL,
    transfer_type ENUM('in','out') NOT NULL,
    transfer_amount BIGINT UNSIGNED NOT NULL,
    accumulated BIGINT UNSIGNED NULL,
    sub_account VARCHAR(64) NULL,
    reference_code VARCHAR(64) NULL,
    description TEXT NULL,
    user_id BIGINT UNSIGNED NULL,
    matched_request_id BIGINT UNSIGNED NULL,
    status ENUM('pending','matched','processed','ignored','invalid') NOT NULL DEFAULT 'pending',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (matched_request_id) REFERENCES credit_topup_requests(id) ON DELETE SET NULL,
    INDEX idx_gateway_date (gateway, transaction_date),
    INDEX idx_code (code),
    INDEX idx_user (user_id),
    INDEX idx_matched_request (matched_request_id),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
